export const WORKFLOW_TEMPLATES = [
  {
    slug: 'dictate-to-claude',
    name: 'Dictate to Claude',
    flow: 'Dictate · LLM · Clipboard',
    summary: 'Speak a rough prompt, tighten it, and copy the result for Claude or another coding agent.',
    bestFor: 'prompt cleanup, agent handoff, voice-first coding',
    workflowHref: '/workflows/dictate-to-claude/',
    jsonHref: '/workflows/templates/dictate-to-claude.json',
    targets: ['Claude', 'Clipboard', '@talkie/cli'],
    localNote: 'Capture and clipboard stay local. The model step can use Claude or Local MLX.',
  },
  {
    slug: 'dictate-to-email',
    name: 'Dictate to Email',
    flow: 'Dictate · LLM · Mail',
    summary: 'Talk through a reply and open a polished draft in Mail.app without sending automatically.',
    bestFor: 'email drafts, follow-ups, review-before-send workflows',
    workflowHref: '/workflows/dictate-to-email/',
    jsonHref: '/workflows/templates/dictate-to-email.json',
    targets: ['Mail.app', 'Clipboard', 'LLM'],
    localNote: 'The draft opens on your Mac. External LLM use is optional and configurable.',
  },
  {
    slug: 'voice-memo-to-obsidian',
    name: 'Voice Memo to Obsidian',
    flow: 'Memo · LLM · Save',
    summary: 'Record a messy thought, distill it, and save Markdown into an Obsidian vault alias.',
    bestFor: 'knowledge capture, local notes, Markdown archives',
    workflowHref: '/workflows/voice-memo-to-obsidian/',
    jsonHref: '/workflows/templates/voice-memo-to-obsidian.json',
    targets: ['Obsidian', '@Notes', 'Markdown'],
    localNote: 'Files land in your own vault path. Use Local MLX if the distill step should stay on device.',
  },
  {
    slug: 'iterate-in-compose',
    name: 'Iterate in Compose',
    flow: 'Memo · Compose · Diff',
    summary: 'Keep the raw memo and create a tighter second pass beside it for comparison.',
    bestFor: 'drafting, editing, preserving original phrasing',
    workflowHref: '/workflows/iterate-in-compose/',
    jsonHref: '/workflows/templates/iterate-in-compose.json',
    targets: ['Compose', '@Drafts', 'Diff'],
    localNote: 'The original and revision stay side by side in your local library or draft folder.',
  },
  {
    slug: 'quick-idea-to-cli',
    name: 'Quick Idea to CLI',
    flow: 'Capture · CLI · Claude',
    summary: 'Capture a thought by voice, pull it later from the terminal, and hand it to an agent.',
    bestFor: 'agent context, terminal workflows, deferred ideas',
    workflowHref: '/workflows/quick-idea-to-cli/',
    jsonHref: '/workflows/templates/quick-idea-to-cli.json',
    targets: ['@talkie/cli', 'Claude CLI', '@Inbox'],
    localNote: 'The captured idea queues locally. The CLI handoff happens when you choose to run it.',
  },
  {
    slug: 'bug-note-to-github',
    name: 'Bug Note to GitHub Issue',
    flow: 'Dictate · Shell · GitHub',
    summary: 'Describe a bug while details are fresh, structure it, and open a GitHub issue with gh.',
    bestFor: 'developer teams, issue triage, reproducible bug reports',
    workflowHref: '/workflows/bug-note-to-github/',
    jsonHref: '/workflows/templates/bug-note-to-github.json',
    targets: ['GitHub', 'gh', 'Shell'],
    localNote: 'Shell execution is allowlisted and reviewable. The GitHub call only runs when configured.',
  },
]

export function getWorkflowTemplate(slug) {
  return WORKFLOW_TEMPLATES.find((template) => template.slug === slug)
}
